# Generated by Django 3.2.5 on 2021-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drug_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='safety_advice_alcohol',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='safety_advice_breast_feeding',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='safety_advice_driving',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='safety_advice_pregnancy',
            field=models.TextField(null=True),
        ),
    ]
